services:
  backend:
    build: ./backend/
    ports:
      - 8000:8000
    command: sh -c "alembic upgrade head && python main.py"
    depends_on:
      - db
    env_file:
      - /backend/.env
    volumes:
      - ./backend/src/cameras/migrations/versions/:/app/src/cameras/migrations/versions/
      - ./backend/logs/:/app/backend/logs/
  
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data_cameras:/var/lib/postgresql/data
  
  bot:
    build: ./bot/
    env_file:
      - ./bot/.env
    volumes:
      - ./bot/logs/:/app/logs/
  
  # video_recording:
  #   build: ./video_recording/
  #   env_file:
  #     - ./video_recording/.env
  #   volumes:
  #     - ./video_recording/videos/:/app/videos/
  #     - ./video_recording/logs/:/app/logs/
  #   command: sh -c "python main.py"
  #   network_mode: host
  #   restart: unless-stopped 

volumes:
  postgres_data_cameras: