services:
  backend:
    build: ./backend/
    ports:
      - 8000:8000
    command: sh -c "alembic upgrade head && python main.py"
    depends_on:
      - db
    env_file:
      - /backend/.env
    volumes:
      - ./backend/src/migrations/versions/:/app/backend/src/migrations/versions/
      - ./backend/logs/:/app/backend/logs/
  
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data_cameras:/var/lib/postgresql/data
  
  facehunter:
    build: ./facehunter/
    command: sh -c "python main.py"
    volumes:
      - ./facehunter/src/facehunter/faces/:/app/src/facehunter/faces/
      - ./test_video.mp4:/app/src/facehunter/test_video.mp4
volumes:
  postgres_data_cameras: