services:
  backend:
    build: ./backend/
    ports:
      - 8000:8000
    command: sh -c "alembic upgrade head && python main.py"
    depends_on:
      - db
    env_file:
      - /backend/.env
    volumes:
      - ./backend/src/cameras/migrations/versions/:/app/backend/src/cameras/migrations/versions/
      - ./backend/logs/:/app/backend/logs/
  
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data_cameras:/var/lib/postgresql/data
  
  bot:
    build: ./bot/
    env_file:
      - ./bot/.env
    volumes:
      - ./bot/logs/:/app/logs/

volumes:
  postgres_data_cameras: